pessoas = input()                                                                                                                            
l3 = int(pessoas)                                                                                                                            
l2 = int(l3*2)                                                                                                                               
l1 = int(l2*2)                                                                                                                               
print(l1)  